In [ ]:
#question 1 

"order encoding is used while there is order in the data and in label encoding tthe data is beign ordered itself by the alphabetical order "

In [ ]:
#question 2 

"it uses a target feature to give the order to the data we can use it the house price model "

In [ ]:
#question 3 

"Covariance is a statistical measure that describes the degree to which two random variables change together. In other words, it quantifies the degree of linear association or relationship between two variables. Covariance indicates whether an increase in one variable corresponds to an increase, decrease, or no change in the other variable."

In [3]:
#question 4 

from sklearn.preprocessing import LabelEncoder
label_encoder_color = LabelEncoder()
label_encoder_size = LabelEncoder()
label_encoder_material = LabelEncoder()

color = ['red', 'green', 'blue']
size = ['small', 'medium', 'large']
material = ['wood', 'metal', 'plastic']

encoded_color = label_encoder_color.fit_transform(color)
encoded_size = label_encoder_size.fit_transform(size)
encoded_material = label_encoder_material.fit_transform(material)

print("Encoded Color: ", encoded_color)
print("Encoded Size: ", encoded_size)
print("Encoded Material: ", encoded_material)

decoded_color = label_encoder_color.inverse_transform(encoded_color)
decoded_size = label_encoder_size.inverse_transform(encoded_size)
decoded_material = label_encoder_material.inverse_transform(encoded_material)

print("Decoded Color: ", decoded_color)
print("Decoded Size: ", decoded_size)
print("Decoded Material: ", decoded_material)


Encoded Color:  [2 1 0]
Encoded Size:  [2 1 0]
Encoded Material:  [2 0 1]
Decoded Color:  ['red' 'green' 'blue']
Decoded Size:  ['small' 'medium' 'large']
Decoded Material:  ['wood' 'metal' 'plastic']


In [4]:
#question 5 

import numpy as np
age = [30, 40, 35, 28, 45]
income = [50000, 60000, 55000, 45000, 70000]
education = [1, 3, 2, 1, 3]
data = np.array([age, income, education])

cov_matrix = np.cov(data)

print("Covariance Matrix:")
print(cov_matrix)


Covariance Matrix:
[[4.930e+01 6.675e+04 6.750e+00]
 [6.675e+04 9.250e+07 8.750e+03]
 [6.750e+00 8.750e+03 1.000e+00]]


In [ ]:
#question 6 

"Ordinl"